title                     : Isham
email                     : mahajan.isham@gmail.com

description               : >-

baseurl                   : ''
url                       : 'https://ishammahajan.github.io'

twitter_username          : isham_mahajan
github_username           : ishammahajan

markdown                  : kramdown
remote_theme              : "mmistakes/minimal-mistakes"
minimal_mistakes_skin     : "dark"

plugins                   :
  - jekyll-feed
defaults:
  - scope                 :
      path                : ''
      type                : posts
    values:
      layout              : single
