locale                    : "en-US"
title                     : "Isham's Blog"
title_separator           : "|"
name                      : "Isham Mahajan"
email                     : mahajan.isham@gmail.com
url                       : 'https://ishammahajan.github.io'
repository                : "ishammahajan/ishammahajan.github.io"

description               : >-


twitter_username          : isham_mahajan
github_username           : ishammahajan

markdown                  : kramdown
search                    : true
remote_theme              : "mmistakes/minimal-mistakes"
minimal_mistakes_skin     : "dark"
permalink                 : /:categories/:title/
breadcrumbs               : true

plugins                   :
  - jekyll-feed
  - jekyll-include-cache
defaults                  :
  - scope                 :
      path                : ''
      type                : posts
    values                :
      layout              : single
      author_profile      : true
      read_time           : true
      share               : true
      related             : true
