locale                    : "en-US"
title                     : "Isham's Blog"
title_separator           : "|"
name                      : "Isham Mahajan"
email                     : mahajan.isham@gmail.com
url                       : 'https://ishammahajan.github.io'
repository                : "ishammahajan/ishammahajan.github.io"

description               : >-


twitter_username          : isham_mahajan
github_username           : ishammahajan

markdown                  : kramdown
search                    : true
remote_theme              : "mmistakes/minimal-mistakes"
minimal_mistakes_skin     : "dark"
permalink                 : /:categories/:title/
breadcrumbs               : true
paginate                  : 5 # amount of posts to show
paginate_path             : /page:num/

plugins                   :
  - jekyll-feed
  - jekyll-include-cache
defaults                  :
  - scope                 :
      path                : ''
      type                : posts
    values                :
      layout              : single
      author_profile      : true
      read_time           : true
      share               : true
      related             : true

author                    :
  name                    : "Isham Mahajan"
  avatar                  : "/assets/images/bio-photo.jpg"
  bio                     : "I try to create."
  location                : "Manipal | Thane"
  links                   :
    - label               : "GitHub"
      icon                : "fab fa-fw fa-github"
      url                 : "https://www.github.com/ishammahajan"
    - label               : "Instagram"
      icon                : "fab fa-fw fa-instagram"
      url                 : "https://www.instagram.com/_.isham_/"
    - label               : "WhatsApp"
      icon                : "fab fa-fw fa-whatsapp"
      url                 : "https:wa.me/8618375066"
